### ISSUE TITLE
object of type 'int' has no len()

### ISSUE THREAD

**Issue by Pizzanomicon** [simon-budig/lamusica#1]
When attempting to run 
`lamusica.py --box=teanola30 -svg=smashmouth_allstar_vocals.svg SMASHMOUTH.vocals-nodrums.AllStar.mid
`
I get:

```
Traceback (most recent call last):
  File "lamusica.py", line 607, in <module>
    notelist = roll.get_compat_band (model)
  File "lamusica.py", line 318, in get_compat_band
    if n.note + self.transpose[n.track % len (self.transpose)] in source_notes
TypeError: object of type 'int' has no len()
```

**Comment by simon-budig** [comment]
I am sorry, I neglected the github repository. This problem has been fixed in my private repository for quite some time, but I've finally managed to sync this repo again...

Sorry for the delay.
